In [25]:
import pandas

In [26]:
df=pandas.read_csv('/content/student_performance.csv')

In [27]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [28]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [29]:
df.shape

(30, 13)

In [30]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')

In [31]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [32]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [33]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [34]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [35]:
df['math_score'].mean()

np.float64(76.06666666666666)

In [36]:
df['science_score'].max()

93

In [37]:
df['english_score'].min()

55

In [38]:
df[df['math_score'] > 80]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [39]:
df[df['gender'] == 'Female']

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [40]:
df.sort_values(by='math_score', ascending=False)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023

In [41]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']

In [42]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,235
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023,246
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023,200
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023,225
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,261

In [43]:
df['math_score'].max()

95

In [44]:
df['science_score'].min()

61

In [45]:
df[df['math_score'] > 80]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,235
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,261
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023,263
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023,274
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023,246
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023,256
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023,262
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023,271
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023,247
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023,238
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023,271

In [46]:
import matplotlib.pyplot as plt

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             30 non-null     int64
 1   name                   30 non-null     object
 2   age                    30 non-null     int64
 3   gender                 30 non-null     object
 4   department             30 non-null     object
 5   semester               30 non-null     int64
 6   math_score             30 non-null     int64
 7   science_score          30 non-null     int64
 8   english_score          30 non-null     int64
 9   programming_score      30 non-null     int64
 10  attendance_percentage  30 non-null     int64
 11  city                   30 non-null     object
 12  admission_year         30 non-null     int64
 13  total_score            30 non-null     int64
dtypes: int64(10), object(4)
memory usage: 3.4+ KB

In [48]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year,total_score
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0,30.000000
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0,228.066667
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0,28.513679
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0,172.000000
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0,203.250000
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0,229.500000
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0,246.750000
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0,274.000000

In [49]:
df.shape

(30, 14)

In [50]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year', 'total_score'],
      dtype='object')

In [53]:
df["total_score"] = (df["math_score"] + df["science_score"] + df["english_score"] + df["programming_score"])

df[["name", "total_score"]]

              name  total_score
0     Aarav Sharma          326
1      Priya Patel          325
2      Rohit Verma          255
3      Sneha Reddy          273
4       Arjun Nair          356
5      Meera Joshi          246
6      Kiran Kumar          247
7      Divya Singh          356
8     Rahul Mishra          236
9       Ananya Das          371
10     Vikram Iyer          295
11     Pooja Gupta          262
12      Suresh Rao          334
13   Kavya Nambiar          285
14     Ajay Tiwari          280
15    Ritu Agarwal          325
16    Manoj Pandey          210
17  Swati Kulkarni          354
18  Deepak Chauhan          252
19    Nisha Kapoor          327
20   Harish Pillai          259
21     Tanvi Mehta          367
22    Sanjay Dubey          228
23   Preeti Saxena          287
24       Amit Bose          336
25      Rekha Nair          285
26   Gaurav Shukla          325
27   Sunita Pillai          232
28      Nitin Jain          271
29  Akanksha Yadav          365

In [54]:
topper = df.loc[df["total_score"].idxmax()]
print("Topper:", topper["name"])
print("Score:", topper["total_score"])

Topper: Ananya Das
Score: 371

In [59]:
dept_avg = df.groupby('department')['total_score'].mean().round(3)

In [60]:
print(dept_avg)

department
Civil               235.800
Computer Science    340.154
Electronics         277.500
Mechanical          267.333
Name: total_score, dtype: float64